version: "3"
services:
  nginx:
    shm_size: 64mb
    image: nginx:1-alpine
    depends_on:
      - wordpress
    ports:
      - 18888:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/advanced-posts-blocks
      - ./:/home/www-data/app
  #
  # WordPress
  #
  wordpress:
    shm_size: 256mb
    image: wordpress:fpm-alpine
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: "mysql:3306"
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_DB_USER: "wordpress"
      WORDPRESS_DB_PASSWORD: "wordpress"
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/advanced-posts-blocks
      - ./:/home/www-data/app

  mysql:
    shm_size: 256mb
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "wordpress"
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d

  installer:
    shm_size: 256mb
    image: wordpress:cli
    depends_on:
      - mysql
      - wordpress
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/advanced-posts-blocks
      - ./:/home/www-data/app
    command: >
      bash /home/www-data/app/docker/sh/wait-for.sh mysql:3306 -t 120 -- bash /home/www-data/app/docker/sh/install.sh 18888

  cli:
    shm_size: 256mb
    image: wordpress:cli
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/advanced-posts-blocks
      - ./:/home/www-data/app

volumes:
  wordpress:
    driver: local
  mysql:
    driver: local
